{
  "formatVersion": "1.1",
  "component": {
    "group": "gg.norisk.webp",
    "module": "linux",
    "version": "26.2.21-main",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.2.21-main"
          }
        }
      ],
      "files": [
        {
          "name": "linux-26.2.21-main.jar",
          "url": "linux-26.2.21-main.jar",
          "size": 2382579,
          "sha512": "40c0bfe32e84cabccfccd992f4a58624aa9ed5968b98c0e72c0acaefed0c1e892edcc6550444f436d9755542812faf39fb6a707447c40cc51feabaf9180b3b14",
          "sha256": "25122d44006fdf7c8573fc3c84749623d2fbc6d712986154e55f5503b1e71d02",
          "sha1": "08b3bcd53dee84c7ca0d53c411f90afed3d9750e",
          "md5": "ee5bb276dc90289f1261a1234bbfab69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.2.21-main"
          }
        }
      ],
      "files": [
        {
          "name": "linux-26.2.21-main.jar",
          "url": "linux-26.2.21-main.jar",
          "size": 2382579,
          "sha512": "40c0bfe32e84cabccfccd992f4a58624aa9ed5968b98c0e72c0acaefed0c1e892edcc6550444f436d9755542812faf39fb6a707447c40cc51feabaf9180b3b14",
          "sha256": "25122d44006fdf7c8573fc3c84749623d2fbc6d712986154e55f5503b1e71d02",
          "sha1": "08b3bcd53dee84c7ca0d53c411f90afed3d9750e",
          "md5": "ee5bb276dc90289f1261a1234bbfab69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "linux-26.2.21-main-sources.jar",
          "url": "linux-26.2.21-main-sources.jar",
          "size": 2382579,
          "sha512": "40c0bfe32e84cabccfccd992f4a58624aa9ed5968b98c0e72c0acaefed0c1e892edcc6550444f436d9755542812faf39fb6a707447c40cc51feabaf9180b3b14",
          "sha256": "25122d44006fdf7c8573fc3c84749623d2fbc6d712986154e55f5503b1e71d02",
          "sha1": "08b3bcd53dee84c7ca0d53c411f90afed3d9750e",
          "md5": "ee5bb276dc90289f1261a1234bbfab69"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "linux-26.2.21-main-javadoc.jar",
          "url": "linux-26.2.21-main-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
