{
  "formatVersion": "1.1",
  "component": {
    "group": "gg.norisk.webp",
    "module": "windows",
    "version": "26.2.11-main",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.2.11-main"
          }
        }
      ],
      "files": [
        {
          "name": "windows-26.2.11-main.jar",
          "url": "windows-26.2.11-main.jar",
          "size": 483794,
          "sha512": "6045a849027018b6cfb51e568e0217c46478e3e080d349e18511ac997294a1de4ec681e7c2830615b633258cb84f52520d070281dc1884fbb6b28e359bce7813",
          "sha256": "832d689c2f7816c5d04ef09aa419af73452ff2e8ac89636f81b938f336043ccc",
          "sha1": "790d1af0bf92ac4db0c219bcbf2957f444f5022f",
          "md5": "936c699788419507fe6652ff6df89300"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.2.11-main"
          }
        }
      ],
      "files": [
        {
          "name": "windows-26.2.11-main.jar",
          "url": "windows-26.2.11-main.jar",
          "size": 483794,
          "sha512": "6045a849027018b6cfb51e568e0217c46478e3e080d349e18511ac997294a1de4ec681e7c2830615b633258cb84f52520d070281dc1884fbb6b28e359bce7813",
          "sha256": "832d689c2f7816c5d04ef09aa419af73452ff2e8ac89636f81b938f336043ccc",
          "sha1": "790d1af0bf92ac4db0c219bcbf2957f444f5022f",
          "md5": "936c699788419507fe6652ff6df89300"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "windows-26.2.11-main-sources.jar",
          "url": "windows-26.2.11-main-sources.jar",
          "size": 483794,
          "sha512": "6045a849027018b6cfb51e568e0217c46478e3e080d349e18511ac997294a1de4ec681e7c2830615b633258cb84f52520d070281dc1884fbb6b28e359bce7813",
          "sha256": "832d689c2f7816c5d04ef09aa419af73452ff2e8ac89636f81b938f336043ccc",
          "sha1": "790d1af0bf92ac4db0c219bcbf2957f444f5022f",
          "md5": "936c699788419507fe6652ff6df89300"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "windows-26.2.11-main-javadoc.jar",
          "url": "windows-26.2.11-main-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
