{
  "formatVersion": "1.1",
  "component": {
    "group": "gg.norisk.webp",
    "module": "windows",
    "version": "26.3.5-main",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.3.5-main"
          }
        }
      ],
      "files": [
        {
          "name": "windows-26.3.5-main.jar",
          "url": "windows-26.3.5-main.jar",
          "size": 2029128,
          "sha512": "91158632c6149af758d2907b2257b2188419f6688e6915c96d0d2987840db22f43010cbff79322734baa1339f053482cb5c92bcc57ef0613580b5582cea36c54",
          "sha256": "4287be1111c2a166117a85769da25123f1536101f18054c6be9cef01d4cd6e13",
          "sha1": "98edbf3d79c530362d3e4f9213711bb9d46a7b4b",
          "md5": "b5159792d507bbfeadbac68a09a7fa2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.3.5-main"
          }
        }
      ],
      "files": [
        {
          "name": "windows-26.3.5-main.jar",
          "url": "windows-26.3.5-main.jar",
          "size": 2029128,
          "sha512": "91158632c6149af758d2907b2257b2188419f6688e6915c96d0d2987840db22f43010cbff79322734baa1339f053482cb5c92bcc57ef0613580b5582cea36c54",
          "sha256": "4287be1111c2a166117a85769da25123f1536101f18054c6be9cef01d4cd6e13",
          "sha1": "98edbf3d79c530362d3e4f9213711bb9d46a7b4b",
          "md5": "b5159792d507bbfeadbac68a09a7fa2a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "windows-26.3.5-main-sources.jar",
          "url": "windows-26.3.5-main-sources.jar",
          "size": 2029128,
          "sha512": "91158632c6149af758d2907b2257b2188419f6688e6915c96d0d2987840db22f43010cbff79322734baa1339f053482cb5c92bcc57ef0613580b5582cea36c54",
          "sha256": "4287be1111c2a166117a85769da25123f1536101f18054c6be9cef01d4cd6e13",
          "sha1": "98edbf3d79c530362d3e4f9213711bb9d46a7b4b",
          "md5": "b5159792d507bbfeadbac68a09a7fa2a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "windows-26.3.5-main-javadoc.jar",
          "url": "windows-26.3.5-main-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
