{
  "formatVersion": "1.1",
  "component": {
    "group": "gg.norisk.webp",
    "module": "macos",
    "version": "26.3.3-main",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.3.3-main"
          }
        }
      ],
      "files": [
        {
          "name": "macos-26.3.3-main.jar",
          "url": "macos-26.3.3-main.jar",
          "size": 2424436,
          "sha512": "d8ae2439ff079f3cc50848c5508c997c9711154a76cb9a8d16eccd0b5001fc12dc4c5b49539acf89496158d6dc82d49d906841f91e95a6da6ca708afdcbf5a57",
          "sha256": "309227219aa9891a3e384dcecd7738e4ebf949dd2f0318fbd06458b6b066d9d1",
          "sha1": "cf49f702d0cd0aafb2b51668c0350431bd147ec4",
          "md5": "91ec0cf67ebe9198336077fccbbce784"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.3.3-main"
          }
        }
      ],
      "files": [
        {
          "name": "macos-26.3.3-main.jar",
          "url": "macos-26.3.3-main.jar",
          "size": 2424436,
          "sha512": "d8ae2439ff079f3cc50848c5508c997c9711154a76cb9a8d16eccd0b5001fc12dc4c5b49539acf89496158d6dc82d49d906841f91e95a6da6ca708afdcbf5a57",
          "sha256": "309227219aa9891a3e384dcecd7738e4ebf949dd2f0318fbd06458b6b066d9d1",
          "sha1": "cf49f702d0cd0aafb2b51668c0350431bd147ec4",
          "md5": "91ec0cf67ebe9198336077fccbbce784"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "macos-26.3.3-main-sources.jar",
          "url": "macos-26.3.3-main-sources.jar",
          "size": 2424436,
          "sha512": "d8ae2439ff079f3cc50848c5508c997c9711154a76cb9a8d16eccd0b5001fc12dc4c5b49539acf89496158d6dc82d49d906841f91e95a6da6ca708afdcbf5a57",
          "sha256": "309227219aa9891a3e384dcecd7738e4ebf949dd2f0318fbd06458b6b066d9d1",
          "sha1": "cf49f702d0cd0aafb2b51668c0350431bd147ec4",
          "md5": "91ec0cf67ebe9198336077fccbbce784"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "macos-26.3.3-main-javadoc.jar",
          "url": "macos-26.3.3-main-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
