{
  "formatVersion": "1.1",
  "component": {
    "group": "gg.norisk.webp",
    "module": "windows",
    "version": "26.2.21-main",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.2.21-main"
          }
        }
      ],
      "files": [
        {
          "name": "windows-26.2.21-main.jar",
          "url": "windows-26.2.21-main.jar",
          "size": 1890513,
          "sha512": "5dde3faa61f3c180ce09184d2bd1a28972cb1d08972a6a71f33b7e5503bf73af515650139df6cc084698f9640cb3180e0775d8bb80b51908f4000ff1efad6adf",
          "sha256": "11db80953c91a3829c2d03813ca7da0ed7e4aea94c5f30c84cb0b41596dd1a4a",
          "sha1": "ac1bfb3c5bfdd5960d668df967d12ff09d5d9aa9",
          "md5": "fd5f1d31a01431876fa0e16631cf5dd0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.2.21-main"
          }
        }
      ],
      "files": [
        {
          "name": "windows-26.2.21-main.jar",
          "url": "windows-26.2.21-main.jar",
          "size": 1890513,
          "sha512": "5dde3faa61f3c180ce09184d2bd1a28972cb1d08972a6a71f33b7e5503bf73af515650139df6cc084698f9640cb3180e0775d8bb80b51908f4000ff1efad6adf",
          "sha256": "11db80953c91a3829c2d03813ca7da0ed7e4aea94c5f30c84cb0b41596dd1a4a",
          "sha1": "ac1bfb3c5bfdd5960d668df967d12ff09d5d9aa9",
          "md5": "fd5f1d31a01431876fa0e16631cf5dd0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "windows-26.2.21-main-sources.jar",
          "url": "windows-26.2.21-main-sources.jar",
          "size": 1890513,
          "sha512": "5dde3faa61f3c180ce09184d2bd1a28972cb1d08972a6a71f33b7e5503bf73af515650139df6cc084698f9640cb3180e0775d8bb80b51908f4000ff1efad6adf",
          "sha256": "11db80953c91a3829c2d03813ca7da0ed7e4aea94c5f30c84cb0b41596dd1a4a",
          "sha1": "ac1bfb3c5bfdd5960d668df967d12ff09d5d9aa9",
          "md5": "fd5f1d31a01431876fa0e16631cf5dd0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "windows-26.2.21-main-javadoc.jar",
          "url": "windows-26.2.21-main-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
