{
  "formatVersion": "1.1",
  "component": {
    "group": "gg.norisk.webp",
    "module": "linux",
    "version": "26.2.11-main",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.2.11-main"
          }
        }
      ],
      "files": [
        {
          "name": "linux-26.2.11-main.jar",
          "url": "linux-26.2.11-main.jar",
          "size": 668345,
          "sha512": "dc276e89b2882bf10a62d4702e8742ed6925a07712a00a7a2c95534c77c6de64a8d752e851d92c98100502842e13dc69d414a4fb24adee173be5c89b57db4f47",
          "sha256": "94a05e3270911a81c7fb83f7e0e4eef1f198d054b505301ebf7e022b5b0b700d",
          "sha1": "db81de9da5ae3a8a18496ade89c93d7787cba9be",
          "md5": "1fa7b89a49f8e0f82e47392ab712c67f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.2.11-main"
          }
        }
      ],
      "files": [
        {
          "name": "linux-26.2.11-main.jar",
          "url": "linux-26.2.11-main.jar",
          "size": 668345,
          "sha512": "dc276e89b2882bf10a62d4702e8742ed6925a07712a00a7a2c95534c77c6de64a8d752e851d92c98100502842e13dc69d414a4fb24adee173be5c89b57db4f47",
          "sha256": "94a05e3270911a81c7fb83f7e0e4eef1f198d054b505301ebf7e022b5b0b700d",
          "sha1": "db81de9da5ae3a8a18496ade89c93d7787cba9be",
          "md5": "1fa7b89a49f8e0f82e47392ab712c67f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "linux-26.2.11-main-sources.jar",
          "url": "linux-26.2.11-main-sources.jar",
          "size": 668345,
          "sha512": "dc276e89b2882bf10a62d4702e8742ed6925a07712a00a7a2c95534c77c6de64a8d752e851d92c98100502842e13dc69d414a4fb24adee173be5c89b57db4f47",
          "sha256": "94a05e3270911a81c7fb83f7e0e4eef1f198d054b505301ebf7e022b5b0b700d",
          "sha1": "db81de9da5ae3a8a18496ade89c93d7787cba9be",
          "md5": "1fa7b89a49f8e0f82e47392ab712c67f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "linux-26.2.11-main-javadoc.jar",
          "url": "linux-26.2.11-main-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
