{
  "formatVersion": "1.1",
  "component": {
    "group": "gg.norisk.webp",
    "module": "macos",
    "version": "26.2.11-main",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.2.11-main"
          }
        }
      ],
      "files": [
        {
          "name": "macos-26.2.11-main.jar",
          "url": "macos-26.2.11-main.jar",
          "size": 554284,
          "sha512": "e9ce8985e5f34bef359f1c83dfe0c91ba8ed59b0180199ed1acecee2d61f2147adb945be4ec30c92c88a6963f00ae954480bc72831c2c904150d12fd16dc14cc",
          "sha256": "428f71e8cb49c6bbb20d643d9390bd6cae62a420a593412f46bff3d54ae5afb0",
          "sha1": "5049951c50d482cf93e434ad03bdf757d923b79b",
          "md5": "6262e368eb0582b5c3682dad498240b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.2.11-main"
          }
        }
      ],
      "files": [
        {
          "name": "macos-26.2.11-main.jar",
          "url": "macos-26.2.11-main.jar",
          "size": 554284,
          "sha512": "e9ce8985e5f34bef359f1c83dfe0c91ba8ed59b0180199ed1acecee2d61f2147adb945be4ec30c92c88a6963f00ae954480bc72831c2c904150d12fd16dc14cc",
          "sha256": "428f71e8cb49c6bbb20d643d9390bd6cae62a420a593412f46bff3d54ae5afb0",
          "sha1": "5049951c50d482cf93e434ad03bdf757d923b79b",
          "md5": "6262e368eb0582b5c3682dad498240b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "macos-26.2.11-main-sources.jar",
          "url": "macos-26.2.11-main-sources.jar",
          "size": 554284,
          "sha512": "e9ce8985e5f34bef359f1c83dfe0c91ba8ed59b0180199ed1acecee2d61f2147adb945be4ec30c92c88a6963f00ae954480bc72831c2c904150d12fd16dc14cc",
          "sha256": "428f71e8cb49c6bbb20d643d9390bd6cae62a420a593412f46bff3d54ae5afb0",
          "sha1": "5049951c50d482cf93e434ad03bdf757d923b79b",
          "md5": "6262e368eb0582b5c3682dad498240b4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "macos-26.2.11-main-javadoc.jar",
          "url": "macos-26.2.11-main-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
