{
  "formatVersion": "1.1",
  "component": {
    "group": "gg.norisk.webp",
    "module": "macos",
    "version": "26.2.21-main",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.2.21-main"
          }
        }
      ],
      "files": [
        {
          "name": "macos-26.2.21-main.jar",
          "url": "macos-26.2.21-main.jar",
          "size": 2022461,
          "sha512": "4474d2e996c4942321b251804481feefc3b950dd80e72fea64c03cb510769db98f3d53458953f90abab33d6a03a26b0dc9b0b38e697077623afc4a9c77060196",
          "sha256": "566955df4809e5fe23527a48fb337d99e5311988a8fef6775452a0f703c942f5",
          "sha1": "ceeddc9d734b26ba8226c5403380e03f54be1efd",
          "md5": "4bedb18daa85f5722a9cf7269dd3d661"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "gg.norisk.webp",
          "module": "core",
          "version": {
            "requires": "26.2.21-main"
          }
        }
      ],
      "files": [
        {
          "name": "macos-26.2.21-main.jar",
          "url": "macos-26.2.21-main.jar",
          "size": 2022461,
          "sha512": "4474d2e996c4942321b251804481feefc3b950dd80e72fea64c03cb510769db98f3d53458953f90abab33d6a03a26b0dc9b0b38e697077623afc4a9c77060196",
          "sha256": "566955df4809e5fe23527a48fb337d99e5311988a8fef6775452a0f703c942f5",
          "sha1": "ceeddc9d734b26ba8226c5403380e03f54be1efd",
          "md5": "4bedb18daa85f5722a9cf7269dd3d661"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "macos-26.2.21-main-sources.jar",
          "url": "macos-26.2.21-main-sources.jar",
          "size": 2022461,
          "sha512": "4474d2e996c4942321b251804481feefc3b950dd80e72fea64c03cb510769db98f3d53458953f90abab33d6a03a26b0dc9b0b38e697077623afc4a9c77060196",
          "sha256": "566955df4809e5fe23527a48fb337d99e5311988a8fef6775452a0f703c942f5",
          "sha1": "ceeddc9d734b26ba8226c5403380e03f54be1efd",
          "md5": "4bedb18daa85f5722a9cf7269dd3d661"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "macos-26.2.21-main-javadoc.jar",
          "url": "macos-26.2.21-main-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
